### ISSUE TITLE
IE9 triggering media-queries erratically (index.php onload)

### ISSUE THREAD

**Issue by isocroft** [synergixe/SynTestRepo#1]
IE9 currently seems to be having problems with properly settling the view once loaded (index.php) as it keeps triggering the media-queries erratically and thereby affecting the view. I haven't tested on IE8 but i'm pretty sure it'll be worse (since IE8 doesn't support media-queries and uses 'respond.js' to mimic that functionality). I have tested in Firefox and Chrome and everything seems to be okay.

**Comment by synergixe** [comment]
Hey Guys!! Good news! As i was reviewing the latest version of 'respond.js', i stumbled on the 'Caveats' section in the README.MD view and found [http://stackoverflow.com/questions/10316247/media-queries-fail-inside-ie9-iframe](this) link which informs on the fact that IE9 has a bug that makes media-queries misbehave when placed in an iframe using externally referenced CSS file(s). I was able to implement a cure (or hack to be fair :( ) by using a query string key of 'nocache' set to a randomly generated string and surprisingly that did it!!
